version: "2"
run:
  go: "1.24"
  concurrency: 4
  timeout: 10m

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - errcheck
    - gosimple
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gocyclo
    - gosec
    - misspell
    - whitespace
    - revive
