// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/telepair/terminal/ent/tenant"
	"github.com/telepair/terminal/ent/user"
)

// TenantCreate is the builder for creating a Tenant entity.
type TenantCreate struct {
	config
	mutation *TenantMutation
	hooks    []Hook
}

// SetEnabled sets the "enabled" field.
func (tc *TenantCreate) SetEnabled(b bool) *TenantCreate {
	tc.mutation.SetEnabled(b)
	return tc
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (tc *TenantCreate) SetNillableEnabled(b *bool) *TenantCreate {
	if b != nil {
		tc.SetEnabled(*b)
	}
	return tc
}

// SetCreatedAt sets the "created_at" field.
func (tc *TenantCreate) SetCreatedAt(t time.Time) *TenantCreate {
	tc.mutation.SetCreatedAt(t)
	return tc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (tc *TenantCreate) SetNillableCreatedAt(t *time.Time) *TenantCreate {
	if t != nil {
		tc.SetCreatedAt(*t)
	}
	return tc
}

// SetUpdatedAt sets the "updated_at" field.
func (tc *TenantCreate) SetUpdatedAt(t time.Time) *TenantCreate {
	tc.mutation.SetUpdatedAt(t)
	return tc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (tc *TenantCreate) SetNillableUpdatedAt(t *time.Time) *TenantCreate {
	if t != nil {
		tc.SetUpdatedAt(*t)
	}
	return tc
}

// SetName sets the "name" field.
func (tc *TenantCreate) SetName(s string) *TenantCreate {
	tc.mutation.SetName(s)
	return tc
}

// SetGivenName sets the "given_name" field.
func (tc *TenantCreate) SetGivenName(s string) *TenantCreate {
	tc.mutation.SetGivenName(s)
	return tc
}

// SetNillableGivenName sets the "given_name" field if the given value is not nil.
func (tc *TenantCreate) SetNillableGivenName(s *string) *TenantCreate {
	if s != nil {
		tc.SetGivenName(*s)
	}
	return tc
}

// SetAvatar sets the "avatar" field.
func (tc *TenantCreate) SetAvatar(b []byte) *TenantCreate {
	tc.mutation.SetAvatar(b)
	return tc
}

// SetPublicKey sets the "public_key" field.
func (tc *TenantCreate) SetPublicKey(s string) *TenantCreate {
	tc.mutation.SetPublicKey(s)
	return tc
}

// SetNillablePublicKey sets the "public_key" field if the given value is not nil.
func (tc *TenantCreate) SetNillablePublicKey(s *string) *TenantCreate {
	if s != nil {
		tc.SetPublicKey(*s)
	}
	return tc
}

// SetAllowRegistration sets the "allow_registration" field.
func (tc *TenantCreate) SetAllowRegistration(b bool) *TenantCreate {
	tc.mutation.SetAllowRegistration(b)
	return tc
}

// SetNillableAllowRegistration sets the "allow_registration" field if the given value is not nil.
func (tc *TenantCreate) SetNillableAllowRegistration(b *bool) *TenantCreate {
	if b != nil {
		tc.SetAllowRegistration(*b)
	}
	return tc
}

// SetAllowedEmailDomains sets the "allowed_email_domains" field.
func (tc *TenantCreate) SetAllowedEmailDomains(s []string) *TenantCreate {
	tc.mutation.SetAllowedEmailDomains(s)
	return tc
}

// SetAdminEmail sets the "admin_email" field.
func (tc *TenantCreate) SetAdminEmail(s string) *TenantCreate {
	tc.mutation.SetAdminEmail(s)
	return tc
}

// SetCustattr sets the "custattr" field.
func (tc *TenantCreate) SetCustattr(m map[string]interface{}) *TenantCreate {
	tc.mutation.SetCustattr(m)
	return tc
}

// SetDescription sets the "description" field.
func (tc *TenantCreate) SetDescription(s string) *TenantCreate {
	tc.mutation.SetDescription(s)
	return tc
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (tc *TenantCreate) SetNillableDescription(s *string) *TenantCreate {
	if s != nil {
		tc.SetDescription(*s)
	}
	return tc
}

// SetID sets the "id" field.
func (tc *TenantCreate) SetID(u uuid.UUID) *TenantCreate {
	tc.mutation.SetID(u)
	return tc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (tc *TenantCreate) SetNillableID(u *uuid.UUID) *TenantCreate {
	if u != nil {
		tc.SetID(*u)
	}
	return tc
}

// AddUserIDs adds the "users" edge to the User entity by IDs.
func (tc *TenantCreate) AddUserIDs(ids ...uuid.UUID) *TenantCreate {
	tc.mutation.AddUserIDs(ids...)
	return tc
}

// AddUsers adds the "users" edges to the User entity.
func (tc *TenantCreate) AddUsers(u ...*User) *TenantCreate {
	ids := make([]uuid.UUID, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return tc.AddUserIDs(ids...)
}

// Mutation returns the TenantMutation object of the builder.
func (tc *TenantCreate) Mutation() *TenantMutation {
	return tc.mutation
}

// Save creates the Tenant in the database.
func (tc *TenantCreate) Save(ctx context.Context) (*Tenant, error) {
	tc.defaults()
	return withHooks(ctx, tc.sqlSave, tc.mutation, tc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (tc *TenantCreate) SaveX(ctx context.Context) *Tenant {
	v, err := tc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tc *TenantCreate) Exec(ctx context.Context) error {
	_, err := tc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tc *TenantCreate) ExecX(ctx context.Context) {
	if err := tc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (tc *TenantCreate) defaults() {
	if _, ok := tc.mutation.Enabled(); !ok {
		v := tenant.DefaultEnabled
		tc.mutation.SetEnabled(v)
	}
	if _, ok := tc.mutation.CreatedAt(); !ok {
		v := tenant.DefaultCreatedAt()
		tc.mutation.SetCreatedAt(v)
	}
	if _, ok := tc.mutation.UpdatedAt(); !ok {
		v := tenant.DefaultUpdatedAt()
		tc.mutation.SetUpdatedAt(v)
	}
	if _, ok := tc.mutation.AllowRegistration(); !ok {
		v := tenant.DefaultAllowRegistration
		tc.mutation.SetAllowRegistration(v)
	}
	if _, ok := tc.mutation.ID(); !ok {
		v := tenant.DefaultID()
		tc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tc *TenantCreate) check() error {
	if _, ok := tc.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "Tenant.enabled"`)}
	}
	if _, ok := tc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Tenant.created_at"`)}
	}
	if _, ok := tc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Tenant.updated_at"`)}
	}
	if _, ok := tc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Tenant.name"`)}
	}
	if v, ok := tc.mutation.Name(); ok {
		if err := tenant.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Tenant.name": %w`, err)}
		}
	}
	if v, ok := tc.mutation.GivenName(); ok {
		if err := tenant.GivenNameValidator(v); err != nil {
			return &ValidationError{Name: "given_name", err: fmt.Errorf(`ent: validator failed for field "Tenant.given_name": %w`, err)}
		}
	}
	if _, ok := tc.mutation.AllowRegistration(); !ok {
		return &ValidationError{Name: "allow_registration", err: errors.New(`ent: missing required field "Tenant.allow_registration"`)}
	}
	if _, ok := tc.mutation.AdminEmail(); !ok {
		return &ValidationError{Name: "admin_email", err: errors.New(`ent: missing required field "Tenant.admin_email"`)}
	}
	if v, ok := tc.mutation.AdminEmail(); ok {
		if err := tenant.AdminEmailValidator(v); err != nil {
			return &ValidationError{Name: "admin_email", err: fmt.Errorf(`ent: validator failed for field "Tenant.admin_email": %w`, err)}
		}
	}
	return nil
}

func (tc *TenantCreate) sqlSave(ctx context.Context) (*Tenant, error) {
	if err := tc.check(); err != nil {
		return nil, err
	}
	_node, _spec := tc.createSpec()
	if err := sqlgraph.CreateNode(ctx, tc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	tc.mutation.id = &_node.ID
	tc.mutation.done = true
	return _node, nil
}

func (tc *TenantCreate) createSpec() (*Tenant, *sqlgraph.CreateSpec) {
	var (
		_node = &Tenant{config: tc.config}
		_spec = sqlgraph.NewCreateSpec(tenant.Table, sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeUUID))
	)
	if id, ok := tc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := tc.mutation.Enabled(); ok {
		_spec.SetField(tenant.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := tc.mutation.CreatedAt(); ok {
		_spec.SetField(tenant.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := tc.mutation.UpdatedAt(); ok {
		_spec.SetField(tenant.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := tc.mutation.Name(); ok {
		_spec.SetField(tenant.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := tc.mutation.GivenName(); ok {
		_spec.SetField(tenant.FieldGivenName, field.TypeString, value)
		_node.GivenName = &value
	}
	if value, ok := tc.mutation.Avatar(); ok {
		_spec.SetField(tenant.FieldAvatar, field.TypeBytes, value)
		_node.Avatar = value
	}
	if value, ok := tc.mutation.PublicKey(); ok {
		_spec.SetField(tenant.FieldPublicKey, field.TypeString, value)
		_node.PublicKey = value
	}
	if value, ok := tc.mutation.AllowRegistration(); ok {
		_spec.SetField(tenant.FieldAllowRegistration, field.TypeBool, value)
		_node.AllowRegistration = value
	}
	if value, ok := tc.mutation.AllowedEmailDomains(); ok {
		_spec.SetField(tenant.FieldAllowedEmailDomains, field.TypeJSON, value)
		_node.AllowedEmailDomains = value
	}
	if value, ok := tc.mutation.AdminEmail(); ok {
		_spec.SetField(tenant.FieldAdminEmail, field.TypeString, value)
		_node.AdminEmail = value
	}
	if value, ok := tc.mutation.Custattr(); ok {
		_spec.SetField(tenant.FieldCustattr, field.TypeJSON, value)
		_node.Custattr = value
	}
	if value, ok := tc.mutation.Description(); ok {
		_spec.SetField(tenant.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if nodes := tc.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.UsersTable,
			Columns: []string{tenant.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// TenantCreateBulk is the builder for creating many Tenant entities in bulk.
type TenantCreateBulk struct {
	config
	err      error
	builders []*TenantCreate
}

// Save creates the Tenant entities in the database.
func (tcb *TenantCreateBulk) Save(ctx context.Context) ([]*Tenant, error) {
	if tcb.err != nil {
		return nil, tcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(tcb.builders))
	nodes := make([]*Tenant, len(tcb.builders))
	mutators := make([]Mutator, len(tcb.builders))
	for i := range tcb.builders {
		func(i int, root context.Context) {
			builder := tcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TenantMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, tcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, tcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, tcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (tcb *TenantCreateBulk) SaveX(ctx context.Context) []*Tenant {
	v, err := tcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tcb *TenantCreateBulk) Exec(ctx context.Context) error {
	_, err := tcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tcb *TenantCreateBulk) ExecX(ctx context.Context) {
	if err := tcb.Exec(ctx); err != nil {
		panic(err)
	}
}
