// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/telepair/terminal/ent/predicate"
	"github.com/telepair/terminal/ent/tenant"
	"github.com/telepair/terminal/ent/user"
)

// TenantUpdate is the builder for updating Tenant entities.
type TenantUpdate struct {
	config
	hooks    []Hook
	mutation *TenantMutation
}

// Where appends a list predicates to the TenantUpdate builder.
func (tu *TenantUpdate) Where(ps ...predicate.Tenant) *TenantUpdate {
	tu.mutation.Where(ps...)
	return tu
}

// SetEnabled sets the "enabled" field.
func (tu *TenantUpdate) SetEnabled(b bool) *TenantUpdate {
	tu.mutation.SetEnabled(b)
	return tu
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (tu *TenantUpdate) SetNillableEnabled(b *bool) *TenantUpdate {
	if b != nil {
		tu.SetEnabled(*b)
	}
	return tu
}

// SetUpdatedAt sets the "updated_at" field.
func (tu *TenantUpdate) SetUpdatedAt(t time.Time) *TenantUpdate {
	tu.mutation.SetUpdatedAt(t)
	return tu
}

// SetName sets the "name" field.
func (tu *TenantUpdate) SetName(s string) *TenantUpdate {
	tu.mutation.SetName(s)
	return tu
}

// SetNillableName sets the "name" field if the given value is not nil.
func (tu *TenantUpdate) SetNillableName(s *string) *TenantUpdate {
	if s != nil {
		tu.SetName(*s)
	}
	return tu
}

// SetGivenName sets the "given_name" field.
func (tu *TenantUpdate) SetGivenName(s string) *TenantUpdate {
	tu.mutation.SetGivenName(s)
	return tu
}

// SetNillableGivenName sets the "given_name" field if the given value is not nil.
func (tu *TenantUpdate) SetNillableGivenName(s *string) *TenantUpdate {
	if s != nil {
		tu.SetGivenName(*s)
	}
	return tu
}

// ClearGivenName clears the value of the "given_name" field.
func (tu *TenantUpdate) ClearGivenName() *TenantUpdate {
	tu.mutation.ClearGivenName()
	return tu
}

// SetAvatar sets the "avatar" field.
func (tu *TenantUpdate) SetAvatar(b []byte) *TenantUpdate {
	tu.mutation.SetAvatar(b)
	return tu
}

// ClearAvatar clears the value of the "avatar" field.
func (tu *TenantUpdate) ClearAvatar() *TenantUpdate {
	tu.mutation.ClearAvatar()
	return tu
}

// SetPublicKey sets the "public_key" field.
func (tu *TenantUpdate) SetPublicKey(s string) *TenantUpdate {
	tu.mutation.SetPublicKey(s)
	return tu
}

// SetNillablePublicKey sets the "public_key" field if the given value is not nil.
func (tu *TenantUpdate) SetNillablePublicKey(s *string) *TenantUpdate {
	if s != nil {
		tu.SetPublicKey(*s)
	}
	return tu
}

// ClearPublicKey clears the value of the "public_key" field.
func (tu *TenantUpdate) ClearPublicKey() *TenantUpdate {
	tu.mutation.ClearPublicKey()
	return tu
}

// SetAllowRegistration sets the "allow_registration" field.
func (tu *TenantUpdate) SetAllowRegistration(b bool) *TenantUpdate {
	tu.mutation.SetAllowRegistration(b)
	return tu
}

// SetNillableAllowRegistration sets the "allow_registration" field if the given value is not nil.
func (tu *TenantUpdate) SetNillableAllowRegistration(b *bool) *TenantUpdate {
	if b != nil {
		tu.SetAllowRegistration(*b)
	}
	return tu
}

// SetAllowedEmailDomains sets the "allowed_email_domains" field.
func (tu *TenantUpdate) SetAllowedEmailDomains(s []string) *TenantUpdate {
	tu.mutation.SetAllowedEmailDomains(s)
	return tu
}

// AppendAllowedEmailDomains appends s to the "allowed_email_domains" field.
func (tu *TenantUpdate) AppendAllowedEmailDomains(s []string) *TenantUpdate {
	tu.mutation.AppendAllowedEmailDomains(s)
	return tu
}

// ClearAllowedEmailDomains clears the value of the "allowed_email_domains" field.
func (tu *TenantUpdate) ClearAllowedEmailDomains() *TenantUpdate {
	tu.mutation.ClearAllowedEmailDomains()
	return tu
}

// SetCustattr sets the "custattr" field.
func (tu *TenantUpdate) SetCustattr(m map[string]interface{}) *TenantUpdate {
	tu.mutation.SetCustattr(m)
	return tu
}

// ClearCustattr clears the value of the "custattr" field.
func (tu *TenantUpdate) ClearCustattr() *TenantUpdate {
	tu.mutation.ClearCustattr()
	return tu
}

// SetDescription sets the "description" field.
func (tu *TenantUpdate) SetDescription(s string) *TenantUpdate {
	tu.mutation.SetDescription(s)
	return tu
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (tu *TenantUpdate) SetNillableDescription(s *string) *TenantUpdate {
	if s != nil {
		tu.SetDescription(*s)
	}
	return tu
}

// ClearDescription clears the value of the "description" field.
func (tu *TenantUpdate) ClearDescription() *TenantUpdate {
	tu.mutation.ClearDescription()
	return tu
}

// AddUserIDs adds the "users" edge to the User entity by IDs.
func (tu *TenantUpdate) AddUserIDs(ids ...uuid.UUID) *TenantUpdate {
	tu.mutation.AddUserIDs(ids...)
	return tu
}

// AddUsers adds the "users" edges to the User entity.
func (tu *TenantUpdate) AddUsers(u ...*User) *TenantUpdate {
	ids := make([]uuid.UUID, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return tu.AddUserIDs(ids...)
}

// Mutation returns the TenantMutation object of the builder.
func (tu *TenantUpdate) Mutation() *TenantMutation {
	return tu.mutation
}

// ClearUsers clears all "users" edges to the User entity.
func (tu *TenantUpdate) ClearUsers() *TenantUpdate {
	tu.mutation.ClearUsers()
	return tu
}

// RemoveUserIDs removes the "users" edge to User entities by IDs.
func (tu *TenantUpdate) RemoveUserIDs(ids ...uuid.UUID) *TenantUpdate {
	tu.mutation.RemoveUserIDs(ids...)
	return tu
}

// RemoveUsers removes "users" edges to User entities.
func (tu *TenantUpdate) RemoveUsers(u ...*User) *TenantUpdate {
	ids := make([]uuid.UUID, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return tu.RemoveUserIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (tu *TenantUpdate) Save(ctx context.Context) (int, error) {
	tu.defaults()
	return withHooks(ctx, tu.sqlSave, tu.mutation, tu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (tu *TenantUpdate) SaveX(ctx context.Context) int {
	affected, err := tu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (tu *TenantUpdate) Exec(ctx context.Context) error {
	_, err := tu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tu *TenantUpdate) ExecX(ctx context.Context) {
	if err := tu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (tu *TenantUpdate) defaults() {
	if _, ok := tu.mutation.UpdatedAt(); !ok {
		v := tenant.UpdateDefaultUpdatedAt()
		tu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tu *TenantUpdate) check() error {
	if v, ok := tu.mutation.Name(); ok {
		if err := tenant.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Tenant.name": %w`, err)}
		}
	}
	if v, ok := tu.mutation.GivenName(); ok {
		if err := tenant.GivenNameValidator(v); err != nil {
			return &ValidationError{Name: "given_name", err: fmt.Errorf(`ent: validator failed for field "Tenant.given_name": %w`, err)}
		}
	}
	return nil
}

func (tu *TenantUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := tu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(tenant.Table, tenant.Columns, sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeUUID))
	if ps := tu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tu.mutation.Enabled(); ok {
		_spec.SetField(tenant.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := tu.mutation.UpdatedAt(); ok {
		_spec.SetField(tenant.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := tu.mutation.Name(); ok {
		_spec.SetField(tenant.FieldName, field.TypeString, value)
	}
	if value, ok := tu.mutation.GivenName(); ok {
		_spec.SetField(tenant.FieldGivenName, field.TypeString, value)
	}
	if tu.mutation.GivenNameCleared() {
		_spec.ClearField(tenant.FieldGivenName, field.TypeString)
	}
	if value, ok := tu.mutation.Avatar(); ok {
		_spec.SetField(tenant.FieldAvatar, field.TypeBytes, value)
	}
	if tu.mutation.AvatarCleared() {
		_spec.ClearField(tenant.FieldAvatar, field.TypeBytes)
	}
	if value, ok := tu.mutation.PublicKey(); ok {
		_spec.SetField(tenant.FieldPublicKey, field.TypeString, value)
	}
	if tu.mutation.PublicKeyCleared() {
		_spec.ClearField(tenant.FieldPublicKey, field.TypeString)
	}
	if value, ok := tu.mutation.AllowRegistration(); ok {
		_spec.SetField(tenant.FieldAllowRegistration, field.TypeBool, value)
	}
	if value, ok := tu.mutation.AllowedEmailDomains(); ok {
		_spec.SetField(tenant.FieldAllowedEmailDomains, field.TypeJSON, value)
	}
	if value, ok := tu.mutation.AppendedAllowedEmailDomains(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, tenant.FieldAllowedEmailDomains, value)
		})
	}
	if tu.mutation.AllowedEmailDomainsCleared() {
		_spec.ClearField(tenant.FieldAllowedEmailDomains, field.TypeJSON)
	}
	if value, ok := tu.mutation.Custattr(); ok {
		_spec.SetField(tenant.FieldCustattr, field.TypeJSON, value)
	}
	if tu.mutation.CustattrCleared() {
		_spec.ClearField(tenant.FieldCustattr, field.TypeJSON)
	}
	if value, ok := tu.mutation.Description(); ok {
		_spec.SetField(tenant.FieldDescription, field.TypeString, value)
	}
	if tu.mutation.DescriptionCleared() {
		_spec.ClearField(tenant.FieldDescription, field.TypeString)
	}
	if tu.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.UsersTable,
			Columns: []string{tenant.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tu.mutation.RemovedUsersIDs(); len(nodes) > 0 && !tu.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.UsersTable,
			Columns: []string{tenant.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tu.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.UsersTable,
			Columns: []string{tenant.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, tu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tenant.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	tu.mutation.done = true
	return n, nil
}

// TenantUpdateOne is the builder for updating a single Tenant entity.
type TenantUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TenantMutation
}

// SetEnabled sets the "enabled" field.
func (tuo *TenantUpdateOne) SetEnabled(b bool) *TenantUpdateOne {
	tuo.mutation.SetEnabled(b)
	return tuo
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (tuo *TenantUpdateOne) SetNillableEnabled(b *bool) *TenantUpdateOne {
	if b != nil {
		tuo.SetEnabled(*b)
	}
	return tuo
}

// SetUpdatedAt sets the "updated_at" field.
func (tuo *TenantUpdateOne) SetUpdatedAt(t time.Time) *TenantUpdateOne {
	tuo.mutation.SetUpdatedAt(t)
	return tuo
}

// SetName sets the "name" field.
func (tuo *TenantUpdateOne) SetName(s string) *TenantUpdateOne {
	tuo.mutation.SetName(s)
	return tuo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (tuo *TenantUpdateOne) SetNillableName(s *string) *TenantUpdateOne {
	if s != nil {
		tuo.SetName(*s)
	}
	return tuo
}

// SetGivenName sets the "given_name" field.
func (tuo *TenantUpdateOne) SetGivenName(s string) *TenantUpdateOne {
	tuo.mutation.SetGivenName(s)
	return tuo
}

// SetNillableGivenName sets the "given_name" field if the given value is not nil.
func (tuo *TenantUpdateOne) SetNillableGivenName(s *string) *TenantUpdateOne {
	if s != nil {
		tuo.SetGivenName(*s)
	}
	return tuo
}

// ClearGivenName clears the value of the "given_name" field.
func (tuo *TenantUpdateOne) ClearGivenName() *TenantUpdateOne {
	tuo.mutation.ClearGivenName()
	return tuo
}

// SetAvatar sets the "avatar" field.
func (tuo *TenantUpdateOne) SetAvatar(b []byte) *TenantUpdateOne {
	tuo.mutation.SetAvatar(b)
	return tuo
}

// ClearAvatar clears the value of the "avatar" field.
func (tuo *TenantUpdateOne) ClearAvatar() *TenantUpdateOne {
	tuo.mutation.ClearAvatar()
	return tuo
}

// SetPublicKey sets the "public_key" field.
func (tuo *TenantUpdateOne) SetPublicKey(s string) *TenantUpdateOne {
	tuo.mutation.SetPublicKey(s)
	return tuo
}

// SetNillablePublicKey sets the "public_key" field if the given value is not nil.
func (tuo *TenantUpdateOne) SetNillablePublicKey(s *string) *TenantUpdateOne {
	if s != nil {
		tuo.SetPublicKey(*s)
	}
	return tuo
}

// ClearPublicKey clears the value of the "public_key" field.
func (tuo *TenantUpdateOne) ClearPublicKey() *TenantUpdateOne {
	tuo.mutation.ClearPublicKey()
	return tuo
}

// SetAllowRegistration sets the "allow_registration" field.
func (tuo *TenantUpdateOne) SetAllowRegistration(b bool) *TenantUpdateOne {
	tuo.mutation.SetAllowRegistration(b)
	return tuo
}

// SetNillableAllowRegistration sets the "allow_registration" field if the given value is not nil.
func (tuo *TenantUpdateOne) SetNillableAllowRegistration(b *bool) *TenantUpdateOne {
	if b != nil {
		tuo.SetAllowRegistration(*b)
	}
	return tuo
}

// SetAllowedEmailDomains sets the "allowed_email_domains" field.
func (tuo *TenantUpdateOne) SetAllowedEmailDomains(s []string) *TenantUpdateOne {
	tuo.mutation.SetAllowedEmailDomains(s)
	return tuo
}

// AppendAllowedEmailDomains appends s to the "allowed_email_domains" field.
func (tuo *TenantUpdateOne) AppendAllowedEmailDomains(s []string) *TenantUpdateOne {
	tuo.mutation.AppendAllowedEmailDomains(s)
	return tuo
}

// ClearAllowedEmailDomains clears the value of the "allowed_email_domains" field.
func (tuo *TenantUpdateOne) ClearAllowedEmailDomains() *TenantUpdateOne {
	tuo.mutation.ClearAllowedEmailDomains()
	return tuo
}

// SetCustattr sets the "custattr" field.
func (tuo *TenantUpdateOne) SetCustattr(m map[string]interface{}) *TenantUpdateOne {
	tuo.mutation.SetCustattr(m)
	return tuo
}

// ClearCustattr clears the value of the "custattr" field.
func (tuo *TenantUpdateOne) ClearCustattr() *TenantUpdateOne {
	tuo.mutation.ClearCustattr()
	return tuo
}

// SetDescription sets the "description" field.
func (tuo *TenantUpdateOne) SetDescription(s string) *TenantUpdateOne {
	tuo.mutation.SetDescription(s)
	return tuo
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (tuo *TenantUpdateOne) SetNillableDescription(s *string) *TenantUpdateOne {
	if s != nil {
		tuo.SetDescription(*s)
	}
	return tuo
}

// ClearDescription clears the value of the "description" field.
func (tuo *TenantUpdateOne) ClearDescription() *TenantUpdateOne {
	tuo.mutation.ClearDescription()
	return tuo
}

// AddUserIDs adds the "users" edge to the User entity by IDs.
func (tuo *TenantUpdateOne) AddUserIDs(ids ...uuid.UUID) *TenantUpdateOne {
	tuo.mutation.AddUserIDs(ids...)
	return tuo
}

// AddUsers adds the "users" edges to the User entity.
func (tuo *TenantUpdateOne) AddUsers(u ...*User) *TenantUpdateOne {
	ids := make([]uuid.UUID, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return tuo.AddUserIDs(ids...)
}

// Mutation returns the TenantMutation object of the builder.
func (tuo *TenantUpdateOne) Mutation() *TenantMutation {
	return tuo.mutation
}

// ClearUsers clears all "users" edges to the User entity.
func (tuo *TenantUpdateOne) ClearUsers() *TenantUpdateOne {
	tuo.mutation.ClearUsers()
	return tuo
}

// RemoveUserIDs removes the "users" edge to User entities by IDs.
func (tuo *TenantUpdateOne) RemoveUserIDs(ids ...uuid.UUID) *TenantUpdateOne {
	tuo.mutation.RemoveUserIDs(ids...)
	return tuo
}

// RemoveUsers removes "users" edges to User entities.
func (tuo *TenantUpdateOne) RemoveUsers(u ...*User) *TenantUpdateOne {
	ids := make([]uuid.UUID, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return tuo.RemoveUserIDs(ids...)
}

// Where appends a list predicates to the TenantUpdate builder.
func (tuo *TenantUpdateOne) Where(ps ...predicate.Tenant) *TenantUpdateOne {
	tuo.mutation.Where(ps...)
	return tuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (tuo *TenantUpdateOne) Select(field string, fields ...string) *TenantUpdateOne {
	tuo.fields = append([]string{field}, fields...)
	return tuo
}

// Save executes the query and returns the updated Tenant entity.
func (tuo *TenantUpdateOne) Save(ctx context.Context) (*Tenant, error) {
	tuo.defaults()
	return withHooks(ctx, tuo.sqlSave, tuo.mutation, tuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (tuo *TenantUpdateOne) SaveX(ctx context.Context) *Tenant {
	node, err := tuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (tuo *TenantUpdateOne) Exec(ctx context.Context) error {
	_, err := tuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tuo *TenantUpdateOne) ExecX(ctx context.Context) {
	if err := tuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (tuo *TenantUpdateOne) defaults() {
	if _, ok := tuo.mutation.UpdatedAt(); !ok {
		v := tenant.UpdateDefaultUpdatedAt()
		tuo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tuo *TenantUpdateOne) check() error {
	if v, ok := tuo.mutation.Name(); ok {
		if err := tenant.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Tenant.name": %w`, err)}
		}
	}
	if v, ok := tuo.mutation.GivenName(); ok {
		if err := tenant.GivenNameValidator(v); err != nil {
			return &ValidationError{Name: "given_name", err: fmt.Errorf(`ent: validator failed for field "Tenant.given_name": %w`, err)}
		}
	}
	return nil
}

func (tuo *TenantUpdateOne) sqlSave(ctx context.Context) (_node *Tenant, err error) {
	if err := tuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(tenant.Table, tenant.Columns, sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeUUID))
	id, ok := tuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Tenant.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := tuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tenant.FieldID)
		for _, f := range fields {
			if !tenant.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != tenant.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := tuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tuo.mutation.Enabled(); ok {
		_spec.SetField(tenant.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := tuo.mutation.UpdatedAt(); ok {
		_spec.SetField(tenant.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := tuo.mutation.Name(); ok {
		_spec.SetField(tenant.FieldName, field.TypeString, value)
	}
	if value, ok := tuo.mutation.GivenName(); ok {
		_spec.SetField(tenant.FieldGivenName, field.TypeString, value)
	}
	if tuo.mutation.GivenNameCleared() {
		_spec.ClearField(tenant.FieldGivenName, field.TypeString)
	}
	if value, ok := tuo.mutation.Avatar(); ok {
		_spec.SetField(tenant.FieldAvatar, field.TypeBytes, value)
	}
	if tuo.mutation.AvatarCleared() {
		_spec.ClearField(tenant.FieldAvatar, field.TypeBytes)
	}
	if value, ok := tuo.mutation.PublicKey(); ok {
		_spec.SetField(tenant.FieldPublicKey, field.TypeString, value)
	}
	if tuo.mutation.PublicKeyCleared() {
		_spec.ClearField(tenant.FieldPublicKey, field.TypeString)
	}
	if value, ok := tuo.mutation.AllowRegistration(); ok {
		_spec.SetField(tenant.FieldAllowRegistration, field.TypeBool, value)
	}
	if value, ok := tuo.mutation.AllowedEmailDomains(); ok {
		_spec.SetField(tenant.FieldAllowedEmailDomains, field.TypeJSON, value)
	}
	if value, ok := tuo.mutation.AppendedAllowedEmailDomains(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, tenant.FieldAllowedEmailDomains, value)
		})
	}
	if tuo.mutation.AllowedEmailDomainsCleared() {
		_spec.ClearField(tenant.FieldAllowedEmailDomains, field.TypeJSON)
	}
	if value, ok := tuo.mutation.Custattr(); ok {
		_spec.SetField(tenant.FieldCustattr, field.TypeJSON, value)
	}
	if tuo.mutation.CustattrCleared() {
		_spec.ClearField(tenant.FieldCustattr, field.TypeJSON)
	}
	if value, ok := tuo.mutation.Description(); ok {
		_spec.SetField(tenant.FieldDescription, field.TypeString, value)
	}
	if tuo.mutation.DescriptionCleared() {
		_spec.ClearField(tenant.FieldDescription, field.TypeString)
	}
	if tuo.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.UsersTable,
			Columns: []string{tenant.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tuo.mutation.RemovedUsersIDs(); len(nodes) > 0 && !tuo.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.UsersTable,
			Columns: []string{tenant.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tuo.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.UsersTable,
			Columns: []string{tenant.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Tenant{config: tuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, tuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tenant.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	tuo.mutation.done = true
	return _node, nil
}
